### ISSUE TITLE
Hostname is not the FQDN

### ISSUE THREAD

**Issue by taylorleese** [martin2110/puppetdb-rundeck#3]
I'm having issues with Rundeck and hostnames and I believe it may be because of the response I'm receiving via the puppetdb-rundeck module. Notice in the partial response below the fqdn is expert-1.prd.mydomain.com, but the hostname field is just expert-1. This causes issues in the Rundeck jobs.

``` yaml
expert-1.prd.mydomain.com:
  tags: Apt,Apt::Params,Apt::Update,Common,Common::Config,Common::Install,Concat::Setup,Expert,Expert::Config,Expert::Install,Expert::Service,Fail2ban,Fail2ban::Params,main,Nginx::Package,Nginx::Package::Debian,Nginx::Service,Nodejs,Nodejs::Params,Ntp,Ntp::Config,Ntp::Install,Ntp::Params,Ntp::Service,Papertrail,Papertrail::Config,Play,Puppet,Puppet::Config,Puppet::Install,Puppet::Service,Resolvconf,Resolvconf::Config,Resolvconf::Dpkg_reconfigure,Resolvconf::Package,Resolvconf::Reload,Rsyslog,Rsyslog::Client,Rsyslog::Config,Rsyslog::Install,Rsyslog::Params,Rsyslog::Service,Settings,Ssh::Hostkeys,Ssh::Knownhosts,Ssh::Params,Ssh::Server,Ssh::Server::Config,Ssh::Server::Install,Ssh::Server::Service,Sudo,Sudo::Config,Sudo::Install,Users,Users::Config,Wget
  hostname: expert-1
  apt_package_updates: ! '[]'
  apt_has_updates: 'true'
  ec2_network_interfaces_macs_02:fa:34:9d:57:63_public_ipv4s: 54.68.236.1
  ec2_public_ipv4: 54.68.236.1
  ec2_metadata: ! '{"ami-id"=>"ami-6ac2a85a", "ami-launch-index"=>"0", "ami-manifest-path"=>"(unknown)",
    "block-device-mapping"=>{"ami"=>"/dev/sda1", "ephemeral0"=>"sdb", "root"=>"/dev/sda1"},
    "hostname"=>"ip-172-31-37-222.us-west-2.compute.internal", "instance-action"=>"none",
    "instance-id"=>"i-58f73b52", "instance-type"=>"c3.4xlarge", "kernel-id"=>"aki-fc8f11cc",
    "local-hostname"=>"ip-172-31-37-222.us-west-2.compute.internal", "local-ipv4"=>"172.31.37.222",
```
